package com.lint.detector.uastscanner;
"import ..."
// An Example of MethodDetector generated by CreatCodeDetector.java. 
//In this example, the method does not have arguments.
public class ExampleMethodDetector extends Detector implements Detector.UastScanner {
    public static final Issue ISSUE = Issue.create(
        "find the using of Example",
        com.android.tools.lint.detector.api.Category.create("ISSUE_MESSAGE", "ISSUE_NUMBER"),
        "briefDescription",
        "explanation",
        6,
        com.android.tools.lint.detector.api.Severity.ERROR,
        new com.android.tools.lint.detector.api.Implementation(ExampleMethodDetector.class, com.android.tools.lint.detector.api.Scope.JAVA_FILE_SCOPE)
    );

    @Nullable
    @Override
    public List<String> getApplicableMethodNames() {
        return java.util.Arrays.asList("Example");
    }

    @Override
    public void visitMehodCall(@NotNull JavaContext context, @NotNull UcallExpression node,
        @NotNull PsiMethod method) {
            if(context.getEvaluator().methodMatches(method, "android.app.Activity", true, "android.content.res.Configuration")) {
                context.report(ISSUE, node, context.getLocation(node), "Find the")
            }
        }

}